### ISSUE TITLE
Handling Missing Backbone Atoms

### ISSUE THREAD

**Issue by amaus** [amaus/jProtein#2]
Missing backbone CAs causes a crash when calculating the CADistanceMatrix. 

```
Exception in thread "main" java.util.NoSuchElementException: No atom of name CA in residue 175: ASP
    at com.aaronpmaus.jProt.protein.Residue.getAtom(Residue.java:192)
    at com.aaronpmaus.jProt.tools.DistanceMatrixCalculator.calculateDistanceMatrix(DistanceMatrixCalculator.java:100)
    at com.aaronpmaus.jProt.metrics.Metrics.<init>(Metrics.java:132)
    at com.aaronpmaus.jProt.executables.JProtMetrics.main(JProtMetrics.java:164)
80001, 1fem_A.pdb, A, 1hbp_A.pdb, A,  ,  ,  , None,  , 4.87856, 98.864
```
1hbp_A.pdb only contains the N atom for Residue 175. This needs to be handled more gracefully.

**Comment by amaus** [comment]
This can either be handled gracefully via exception handling, or the PDB File Reader should ignore residues that are missing crucial backbone atoms (in the future it should be able to fill in missing atoms).

To handle this with exception handling, the DistanceMatrixCalculator would need to ignore residues missing CA atoms, but this would present a problem to the Metrics class. For comparing two structures, Metrics depends on two CADistanceMatrices with the same dimensions and calculated from those residues that have been aligned between the two sequences. If one matrix ignores a residue, the other one will need to ignore the corresponding aligned residue.

A simpler solution for now is to only construct and add residues to Proteins that have their N, CA, and C atoms. (Requiring N and C is looking forward to needing to calculate dihedral angles.) Then, only those residues will be used in the alignment and subsequence distance matrices.
